#!/bin/bash

# Extract data using jq
name=$(jq -r '.name' data.json | sed 's/^./\u&/')  # Capitalize first letter
height=$(jq -r '.height' data.json | awk '{print $1 / 10}')  # Convert to meters
weight=$(jq -r '.weight' data.json | awk '{print $1 / 10}')  # Convert to kg
type=$(jq -r '.types[0].type.name' data.json | sed 's/^./\u&/')  # First type, capitalize

# Format output
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
